services:
  familybot:
    # 1. 明确镜像名字（方便后续 docker compose push 发布）
    image: 254521335/familybot:latest
    # 2. 本地构建
    build: .
    container_name: familybot_server
    # 🚀 增加环境变量，明确告诉 Python 和 操作系统使用上海时区
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
      # 🚀 将树莓派宿主机的时间文件只读挂载给容器，保持硬件时间绝对一致
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always